<?php

namespace app\modules\admin\controllers;

use app\models\Comment;
use app\models\FileSearch;
use app\models\SearchForm;
use app\models\User;
use app\other\DbHelper;
use Exception;
use Yii;
use app\models\LoginForm;
use app\models\RegisterForm;
use app\models\FileForm;
use yii\base\ErrorException;
use yii\helpers\Url;
use yii\web\Response;
use yii\web\UploadedFile;
use yii\filters\VerbFilter;

class CommentController extends \app\controllers\CommentController {
    public $layout = 'main';

    public function beforeAction($action)
    {
        if (!Yii::$app->user->can('allFiles')){
            $this->redirect('../../site/error');
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionDelete(){
        $commentId = Yii::$app->request->get('id');
        //если кто-нибудь введет экшн на удаление
        //то сделать это будет нельзя
        $model = Comment::find()->where(['id'=>$commentId])->one();
        $fileId = $model->fileId;
        $model->deleteComment();
        return $this->redirect(array("file/view",'id' =>$fileId));
    }
}