<?php

namespace app\modules\admin\controllers;

use app\modules\admin\models\FileSearch;
use Yii;

class SiteController extends \app\controllers\SiteController {
    public $layout = 'main';

    public function beforeAction($action)
    {
        if (!Yii::$app->user->can('allFiles')){
            $this->redirect('../../site/index');
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    //страница загрузок пользователя
    public function actionLastloads(){

        $searchModel = new FileSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('lastloads',[
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider
        ]);
    }
}