<?php

namespace app\modules\api\v1\controllers;

use Yii;
use yii\filters\ContentNegotiator;
use yii\rest\ActiveController;
use yii\web\Response;

class MyApiController extends ActiveController{

    public $serializer = [
        'class' => 'yii\rest\Serializer',
        'collectionEnvelope' => 'items'
    ];

    public function checkAccess($action, $model = null, $params = [])
    {
        return true;
    }

    public function actions()
    {
        $actions = parent::actions();
        unset($actions['delete'],$actions['update'],$actions['create']);
        return $actions;
    }

    //чтобы следовать принципу рест
    //что нельзя сохранять состояние
    public function beforeAction($action)
    {
        Yii::$app->user->logout();
        Yii::$app->session->destroy();
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function afterAction($action, $result)
    {
        Yii::$app->user->logout();
        Yii::$app->session->destroy();
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }

    //только гет запросы
    public function behaviors()
    {
        return [
            'contentNegotiator' => [
                'class' => ContentNegotiator::className(),
                'formatParam' => '_format',
                'formats' => [
                    'application/json' => Response::FORMAT_JSON,
                    'application/xml' => Response::FORMAT_XML,

                ]
            ],
            'verbs' => [
                'class' => \yii\filters\VerbFilter::className(),
                'actions' => [
                    'index'  => ['GET'],
                    'view'   => ['GET'],

                ],
            ],
        ];
    }
}